Default: &defaults
  database: timetracker.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: timetracker_test.sqlite3
  <<: *defaults

Staging:
  database: timetracker_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: timetracker_production.sqlite3
  poolsize: 100
  <<: *defaults
